### ISSUE TITLE
Airport updated events fail in tiles service

### ISSUE THREAD

**Issue by reskume** [openAIP/openaip#154]
` openaip.core-api-eb5163e4-b97a-4501-8dcd-185bd3951e51] [2022-04-22T13:07:45.877Z]: Event scheduled for retry. Failed to handle openaip.core.v1.airport.rfc.applied event with strategy AirportUpdatedStrategy. TypeError: assert failed: expected Object to be Object
    at assertImpl (/usr/src/app/node_modules/check-types/src/check-types.js:827:11)
    at Object.object (/usr/src/app/node_modules/check-types/src/check-types.js:787:7)
    at Function.transformToFeatureData (/usr/src/app/models/entities/airport-feature-model.js:48:54)
    at AirportUpdatedStrategy.handle (/usr/src/app/events/strategies/airport-updated-strategy.js:35:65)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) `

**Comment by reskume** [comment]
Has not reappeared within the last 14 days. Closing.
